#!/usr/bin/env bash
#Bash script that displays 1 - 20

i=1
while (( i<=20 )); do
    if [ $i == 4 ]; then
        echo "$i"
	echo "bad luck from China"
    elif [ $i == 9 ];  then
        echo "$i"
        echo "bad luck from Japan "
    elif [ $i == 17 ];  then
        echo "bad luck from Italy "
    else
    	echo "$i"
    fi
    (( i++ ))
done
