#!/usr/bin/env bash
#Bash script that displays time

hour=0
minutes=1
while (( hour <= 12 )); do
    echo "Hour: $hour"
    while (( minutes < 60 )); do
	echo $minutes
	(( minutes++ ))
    done
    minutes=1
    (( hour++ ))
done
