#!/usr/bin/env bash
#Bash script that displays time

hour=0
minutes=0
while (( hour < 12 )); do
    echo "Hour: $hour"
    while (( minutes < 60 )); do
	echo $minutes
	(( minutes++ ))
    done
    minutes=0
    (( hour++ ))
done
